<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NODE990" name="Test-method test" tests="1" failures="1" timestamp="22 Nov 2021 04:44:33 GMT" time="106.703" errors="0">
  <testcase name="feature" time="105.915" classname="runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [PAYMENT SUCCESS] but found [PAYMENT FAILED]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [PAYMENT SUCCESS] but found [PAYMENT FAILED]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: expected [PAYMENT SUCCESS] but found [PAYMENT FAILED]
	at com.weather.shopper.app.steps.WeatherShopperDefinition.verify_the_Customer_payment_Status(WeatherShopperDefinition.java:254)
	at âœ½.Then Verify the Customer payment Status "PAYMENT SUCCESS"(WeatherShopper.feature:21)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Test-method test -->
